services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 settings.asgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - sqlite_data:/app
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A settings worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - web

  celery_beat:
    build: .
    command: celery -A settings beat -l info
    env_file:
      - .env
    depends_on:
      - redis
      - web

  flower:
    build: .
    command: celery -A settings flower --port=5555 --basic_auth=${BLOG_FLOWER_USER}:${BLOG_FLOWER_PASSWORD}
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  sqlite_data: